---
title: "Acceso a la Justicia y Litigio Constitucional"
output: pdf_document
---


```{r, include=FALSE}
library(readr)
martes <- as.Date ("2024-08-13")
viernes <- as.Date("2024-08-16")

advdate <- function(obj, adv) {
  Sys.setlocale("LC_TIME", "es_ES")
  tmon <- obj + 7*(adv-1)
  tmon <- format(tmon, format="%d/%m")
  zadv <- sprintf("%02d", adv)
  dia <- weekdays(obj)
  tmp <- paste0("Semana ",zadv, ", ", dia,' ', tmon)
  return(tmp)
}
```

Demián Zayat
dzayat@derecho.uba.ar

## Programa

En este curso analizaremos el derecho de acceder a la justicia, su fuente constitucional, sus garantías de funcionamiento y sus mayores problemas y dificultades para su ejercicio.

La visión liberal del derecho da por supuesto que cualquier persona podrá acceder a la justicia cuando su derecho haya sido afectado, vulnerado o amenazado. El presupuesto sobre el que descanza nuestro sistema jurídico es que el Poder Judicial podrá entender y propender a la solución de cualquier conflicto de derechos. Sin embargo, existen diversas causas que hacen que los tribunales y la protección judicial no sea para todas las personas igualmente accesible. Algunas tendrán muchas menos dificultades y otras deberán vencer muchas más barreras para poder hacer llegar su reclamo a los jueces.

Existen aún hoy algunas leyes y normativas que hacen que este acceso sea especialmente dificil para ciertos grupos. En esos casos, la solución podrá ser --paradójicamente-- vía un proceso constitucional.

Sin embargo, también existen supuestos de grupos con mayores dificultades para hacer valer sus derechos ya no por una normativa expresa, sino por diversas prácticas de los operadores judiciales y estatales en general. Estos casos son más dificiles de identificar, aunque inciden de un modo igual o de mayor performatividad. Así, muchas veces puede verse que la respuesta judicial resulta patriarcal, xenófoba, racista, hegemónica, etc.

En este curso haremos una revisión sobre la normativa constitucional involucrada en el derecho de acceso a la justicia, tomaremos nota de las garantías procesales que establece la constitución para su eficacia, y analizaremos de modo crítico cómo y por qué existen grupos identitarios de población que suele tener mayores dificulades de acceso a los tribunales.

## Objetivo

El objetivo del curso es discutir y analizar de modo crítico las diversas barreras que afectan al acceso a la justicia, sus aspectos centrales, y su dimensión estructural. La idea es poder analizar problemas jurídicos desde el punto de vista del acceso a la justicia y decidir estrategias para superarlas.

## Metodología

Será un curso con un componente teorico sobre el derecho de acceso a la justicia y sus garantías de funcionamiento, y práctico en el análisis de la situación de los problemas que los grupos identitarios tienen en particular. Este aspecto práctico partirá del análisis de diversas investigaciones empíricas sobre cuáles son estas dificultades, y la discusión sobre cómo fue resuelta tanto por los tribunales locales como regionales o internacionales.

Se espera que les estudiantes puedan leer la bibliografía indicada de modo previo a cada clase, y que los encuetros funcionen  no para repetir sino para discutir la literatura indicada.

Habrá un único examen presencial al final de la cursada.

## Cronograma y bibliografía

### `r advdate(viernes, 1)`. Unidad 1. Presentación

Presentación de los objetivos y metodología del curso. Introducción al derecho de acceso a la justicia. Dimensión instrumental y dimensión sustantiva del derecho. Movimiento de Acceso a la Justicia. Reconocimiento constitucional.

-   Maurino, Gustavo y Sucunza Matías, "Acceso a la Justicia", en Gargarella- Guidi *Comentarios de la Constitución de la Nación Argentina*, tomo 2, pp 895-929, puntos 1 y 2, [aca](https://drive.google.com/file/d/1Gj7BF0AtPkcnPp7YI7-M2oU-olQHS_I9/view?usp=sharing)


### `r advdate(martes, 2)` Unidad 1. Estándares internacionales 


-   Maurino, Gustavo y Sucunza Matías, "Acceso a la Justicia", en Gargarella- Guidi *Comentarios de la Constitución de la Nación Argentina*, tomo 2, pp 895-929, puntos 3 y 4, [aca](https://drive.google.com/file/d/1Gj7BF0AtPkcnPp7YI7-M2oU-olQHS_I9/view?usp=sharing).

-   Reglas de Brasilia sobre Acceso a la Justicia de las Personas con vulnerabilidad con la actualización de 2018, [en este link](http://www.cumbrejudicial.org/comision-de-seguimiento-de-las-reglas-de-brasilia/documentos-comision-de-seguimiento-de-las-reglas-de-brasilia/item/817-cien-reglas-de-brasilia-actualizadas-version-abril-2018-xix-cumbre-judicial-asamblea-plenaria-san-francisco-de-quito)

- Borrador de Convenio Iberoamericano sobre Acceso a la Justicia [aca](https://drive.google.com/file/d/1ZvhBoVmS245Mt4_mxBN_GJOdlh1jDEL5/view?usp=sharing)


### `r advdate(viernes, 2)` Unidad 2. Concepto clásico y estructural


Patrocinio letrado. Requerir un patrocinio letrado puede ser difícil en muchos casos. ¿Es una garantía útil? Ahora, son todes les abogades iguales? Por qué tener dinero es relevante para el sistema judicial? Concepciones clásica y estructural del acceso a la justicia.

-   Gallanter, "Por qué los poseedores salen adelante?, [link](https://drive.google.com/file/d/1Fj3STLmXxHrJglgGgs5JUtDjXy0DSJ3o/view?usp=sharing)

- Bohmer, "Igualadores Retóricos", [aca](https://drive.google.com/file/d/0B50ljTnhr79kMWQ2OTgzYzMtNGNiNS00YjQxLThjYjYtYzg2YWYyNzc0MTlh/view?usp=sharing&resourcekey=0-QzTl1yGSNgnHMOI_ICHjEg)



### `r advdate(martes, 3)`. Unidad 3. La Agenda estructural - Víctimas


-   CELS, "El acceso a la justicia como una cuestión de derechos humanos", en Informe Anual 2016, [acá](https://drive.google.com/file/d/1qH6DsnHctmesy6nje2f5NgCyowQ0PkyM/view?usp=sharing) El acceso a la justicia como una cuestión de derechos humanos

-   Piqué, María, "Los derechos de las víctimas de delitos en nuestra Constitución", disponible [aca](https://drive.google.com/file/d/1NaUqgIjcAosZx6OCPuJzcdG3sbKrqfaC/view?usp=sharing)

- Declaración de Karina Gimenez, a partir del minuto 28 hasta el minuto 35.

<iframe src="https://drive.google.com/file/d/1ARawcLLXQ_35LuElRaTyZGEHzDAWGr3t/preview" width="560" height="315" allow="autoplay"></iframe>


### `r advdate(viernes, 3)`. Unidad 3. La práctica - Migrantes

En esta unidad comenzaremos a ver cómo son afectados algunos grupos en particular.

a.  Migrantes Expulsiones. Caso Vanessa Gomez

-   Expediente judicial CAF 067668/2018 [retencion](https://drive.google.com/file/d/1MszNbvuQgl56ukSCbql4ggAAKyiia5Bs/view?usp=sharing), [captura](https://drive.google.com/file/d/11RSJ0lXuMKwhQy-gVHfODbc-AH1fBE0j/view?usp=sharing) y [apelacion](https://drive.google.com/file/d/1xsXyT2y3F7sGL8yhK8kG6GTfhkYi7nVw/view?usp=sharing)

-   Oteiza y Zayat, A treinta años de la CDN, [aca](https://drive.google.com/file/d/1rZbIfh3834THG1K07moFq1Cgp_zmYtsk/view?usp=sharing)

- CSJN, Fallo "Zuluaga Celemin" del 13/10/2022



### `r advdate(martes, 4)`. Unidad 3. La práctica - Situación de Calle

b.  Usurpaciones y derecho de defensa

-   Ricciardi y Zayat, *El derecho de defensa en los casos de usurpaciones en la Ciudad de Buenos Aires: un estudio empírico*, en Revista Institucional de la Defensa Pública de la CABA N° 1, disponible [acá](https://drive.google.com/file/d/1KeqFSqkZ2aBrHXkRcIaZCVu6AMSaX7zH/view?usp=sharing)

- Protocolo de Salud Mental, [aca](https://drive.google.com/file/d/1_1DCvbeTGT8gLp9pAMsCejJeJPs-2mj2/view?usp=sharing)

### `r advdate(viernes, 4)`. Unidad 3. La práctica

b.  Personas con discapacidad

-   Corte IDH, caso "Furlan y familiares c. Argentina", disponible [aca](https://www.corteidh.or.cr/docs/casos/articulos/seriec_246_esp.pdf), y un resumen oficial [aca](https://www.corteidh.or.cr/docs/casos/articulos/resumen_246_esp.pdf)

- CSJN, "R. M.J s/Insania", [aca](https://drive.google.com/file/d/1c29zw3cQDmwNGuO-GDR15KUq7Xc-UZJb/view?usp=sharing)

- CSJN, "Asociación Francesa de Beneficencia" [aca](https://drive.google.com/file/d/1hVROXu_IFbswD_0UtcBpXPZ0gEbTIiQJ/view?usp=share_link)

- CSJN, "Institutos Médicos Antártida s/ quiebra s/ inc. de verificación (R.A.F. y L.R.H. de F)" [aca](https://drive.google.com/file/d/1THtTAOVsLhI8y5mQq5mNTLrt-LFdFc-K/view?usp=sharing)

- CSJN, Ejecuciones contra el Estado [aca](https://drive.google.com/file/d/1X2oK8aGhqhadJ7YkQCHktaT49Ypk5udZ/view?usp=share_link)

### `r advdate(martes, 5)`. Unidad 3. La práctica -Niñeces

c. Niñeces

  - Romina Faerman, [Las decisiones de los NNA a la luz del principio de autonomía](https://drive.google.com/file/d/1vjWDNx026ng38dl2I4G_ojXGlBQt23TT/view?usp=sharing)
 
  - MPT CABA, [Violencia contra Niños, Niñas y Adolescentes](https://drive.google.com/file/d/1lc3H955K8Wx1-7mdtDAJX--CBBcqXfuX/view?usp=sharing), presentado por Romina Faerman (en especial capítulo 2)
  

### `r advdate(viernes, 5)`. Unidad 3. La práctica - LGBTIQ

d.  LGBT Trans

-   Informe sombra CEDAW 2016, [aca](https://drive.google.com/file/d/1Zv0TtTTzgt5N4vSBEo3F7UjiayBQ2BIx/view?usp=sharing)

-   Violencia institucional contra personas trans, [ponencia](https://drive.google.com/file/d/1NWDuVTHVpSSWbHTuvP6WPAy6waXvDyXo/view)

- Caso de Luz Aime, [aca](http://cosecharoja.org/absolvieron-a-luz-aime/)

Les dejo también el decreto del [cupo laboral trans](http://servicios.infoleg.gob.ar/infolegInternet/anexos/340000-344999/341808/norma.htm) y la 
[ley 27.636](http://servicios.infoleg.gob.ar/infolegInternet/anexos/350000-354999/351815/norma.htm)



### `r advdate(martes, 6)`. Unidad 3. La práctica

Unidad 3. La práctica - Mujeres

e.  Mujeres

- Pique y Fernandez Valle, "La garantía de imparcialidad judicial desde la perspectiva de género"  [aca](https://drive.google.com/file/d/1atsNG8fNfxcBruDPtPve0N3AmUf6OA3h/view?usp=sharing)

- Recusación Luz Aime [aca](https://drive.google.com/file/d/1ZWe1xva3x_Y0ttVg2CZ4eliKBj-8bbBy/preview)

- CSJN, Fallo Rizzi, 16/05/2024

- Alegato de cierre Ministerio Público Fiscal [Luz Aime](https://youtu.be/ZKH82JYVLgc)

<iframe width="560" height="315" src="https://www.youtube.com/embed/ZKH82JYVLgc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

### `r advdate(viernes, 6)`No hay clases


### `r advdate(martes, 7)`. Unidad 3. La práctica - Mujeres

e. Mujeres (cont)

-   Inecip, casos de violencia de género, [aca](https://inecip.org/publicaciones/herramientas-jurisprudenciales-para-el-litigio-con-perspectiva-de-genero/). Leer la introducción y las fichas 1, 3, 5 y 6.

-   CEDAW, Observación General 33, disponible [acá](https://drive.google.com/file/d/1j3suY4Q3JhS5EzbAvs6_K6XSbQsOQ7D7/view?usp=sharing)

- Ley de Protección integral conta la Mujer [aca](http://servicios.infoleg.gob.ar/infolegInternet/anexos/150000-154999/152155/texact.htm) 

Dejo por aca el video de [Rita Segato](https://youtu.be/prUqWHKnUd4)

<iframe width="560" height="315" src="https://www.youtube.com/embed/prUqWHKnUd4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>



### `r advdate(viernes, 7)`. Unidad 3. La práctica - Afro

e.  Africanos y afrodescendientes

-   Informe Defensoria CABA, [aca](https://drive.google.com/file/d/1vIoZ7GBl8fwXbZWhqoCxqOHsHMvP7Dki/view?usp=sharing)

-   Angela Davis, "Raza, Mujeres y clase", Violación, racismo y el mito del violador negro, [capítulo 11](https://drive.google.com/file/d/1ghSHi12WUBBQlkcBQYiA5--Z_rGMnndc/view?usp=sharing) (o aca el [libro entero](https://drive.google.com/file/d/1dKW89DDQlKGgsKIE74Mi7i6pnmdTvDxn/view?usp=sharing))

-   Grupo de Trabajo sobre Afrodescendientes, visita a [Argentina](http://daccess-ods.un.org/access.nsf/Get?Open&DS=A/HRC/42/59/Add.2&Lang=S)


Acá el video de la charla TED de Kimberle Crenshaw sobre interseccionalidad

<iframe width="560" height="315" src="https://www.youtube.com/embed/akOe5-UsQ2o" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

### `r advdate(martes, 8)`. Unidad 3. La práctica - Pueblos originarios

f.  Pueblos originarios

- Comite DH, NFL, [aca](https://drive.google.com/file/d/1CP_TpEaI6XXZIb3ACuyqa8XFPuvbdR3f/view?usp=sharing)

- Inadi, Dictamen Colihueque, [aca](https://drive.google.com/file/d/1_t9jnOgqHc9qw7PyU6nuJS0_VORXtdLj/view?usp=sharing¨)


### `r advdate(viernes, 8)`. Unidad 4. Litigio Constitucional

Estándares de la Corte Suprema para facilitar el acceso a la justicia: 

- CSJN [Halabi](https://drive.google.com/file/d/1EcDi8VnbuUNH7DlaRPhTMit0IGLLGn0d/view?usp=sharing)

- CSJN [Padec](https://drive.google.com/file/d/186eN_fSToqx4d_W2fRI2pckZA3a5CWCH/view?usp=sharing)

- Amparo colectivo [DADSE](https://drive.google.com/file/d/1g6gfDr5m3UJ8ZzcQErBujPCrSV_V3gCp/view?usp=drive_link)


### `r advdate(martes, 9)`. Examen final presencial

